# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_number',
            new_name='contact_number',
        ),
    ]
