# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20171219_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='media/image.jpg', upload_to='contact/%Y/%m/%d'),
        ),
    ]
