# Generated by Django 2.0 on 2017-12-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
