# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_contact_image'),
        ('directory', '0004_image_image'),
    ]

    operations = [
    ]
